/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import aeropuertos.Central;
import java.util.concurrent.atomic.AtomicInteger;

/**
 *
 * @author lucia
 */
public class Menu extends javax.swing.JFrame {
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        botonPausar = new javax.swing.JToggleButton();
        botonReanudar = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JSeparator();
        bgMadrid = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textoNumPasajeros = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textoBusA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textoHangar = new javax.swing.JTextField();
        textoTaller = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textoBusC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textoEstacionamiento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textoPuerta1 = new javax.swing.JTextField();
        textoPuerta2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textoPuerta3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textoPuerta4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textoPuerta5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textoPuerta6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        textoRodaje = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        textoPista1 = new javax.swing.JTextField();
        textoPista2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        textoPista3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        textoPista4 = new javax.swing.JTextField();
        bgAero = new javax.swing.JPanel();
        textoAeroBaMa = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        textoAeroMaBa = new javax.swing.JTextField();
        bgBarcelona = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        textoNumPasajeros1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        textoBusA1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        textoHangar1 = new javax.swing.JTextField();
        textoTaller1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        textoBusC1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        textoEstacionamiento1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        textoPuerta7 = new javax.swing.JTextField();
        textoPuerta8 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        textoPuerta9 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        textoPuerta10 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        textoPuerta11 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        textoPuerta12 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        textoRodaje1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        textoPista5 = new javax.swing.JTextField();
        textoPista6 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        textoPista7 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        textoPista8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(204, 204, 204));
        bg.setPreferredSize(new java.awt.Dimension(830, 580));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonPausar.setText("Pausar");
        botonPausar.setPreferredSize(new java.awt.Dimension(80, 23));
        botonPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPausarActionPerformed(evt);
            }
        });
        bg.add(botonPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        botonReanudar.setText("Reanudar");
        botonReanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReanudarActionPerformed(evt);
            }
        });
        bg.add(botonReanudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 818, 11));

        bgMadrid.setBackground(new java.awt.Color(204, 204, 204));
        bgMadrid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nº pasajeros en Aeropuerto:");
        bgMadrid.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        textoNumPasajeros.setEditable(false);
        bgMadrid.add(textoNumPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 230, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Vía Aeropuerto:");
        bgMadrid.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));

        textoBusA.setEditable(false);
        textoBusA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoBusAActionPerformed(evt);
            }
        });
        bgMadrid.add(textoBusA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 110, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hangar:");
        bgMadrid.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        textoHangar.setEditable(false);
        bgMadrid.add(textoHangar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 340, -1));

        textoTaller.setEditable(false);
        bgMadrid.add(textoTaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 340, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Taller:");
        bgMadrid.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Vía Ciudad :");
        bgMadrid.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        textoBusC.setEditable(false);
        bgMadrid.add(textoBusC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 110, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Área de estacionamiento:");
        bgMadrid.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        textoEstacionamiento.setEditable(false);
        bgMadrid.add(textoEstacionamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 250, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Puerta 1 (E):");
        bgMadrid.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, -1));

        textoPuerta1.setEditable(false);
        textoPuerta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta1ActionPerformed(evt);
            }
        });
        bgMadrid.add(textoPuerta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 120, -1));

        textoPuerta2.setEditable(false);
        textoPuerta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta2ActionPerformed(evt);
            }
        });
        bgMadrid.add(textoPuerta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 120, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Puerta 2:");
        bgMadrid.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 90, -1));

        textoPuerta3.setEditable(false);
        textoPuerta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta3ActionPerformed(evt);
            }
        });
        bgMadrid.add(textoPuerta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 120, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Puerta 3:");
        bgMadrid.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 90, -1));

        textoPuerta4.setEditable(false);
        textoPuerta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta4ActionPerformed(evt);
            }
        });
        bgMadrid.add(textoPuerta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 130, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Puerta 4:");
        bgMadrid.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 50, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Puerta 5:");
        bgMadrid.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, -1));

        textoPuerta5.setEditable(false);
        textoPuerta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta5ActionPerformed(evt);
            }
        });
        bgMadrid.add(textoPuerta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 130, -1));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Puerta 6 (DE):");
        bgMadrid.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 80, -1));

        textoPuerta6.setEditable(false);
        textoPuerta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta6ActionPerformed(evt);
            }
        });
        bgMadrid.add(textoPuerta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 130, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Aeropuerto de Madrid");
        bgMadrid.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 120, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Área rodaje:");
        bgMadrid.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        textoRodaje.setEditable(false);
        bgMadrid.add(textoRodaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 320, -1));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Pista 1:");
        bgMadrid.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 90, -1));

        textoPista1.setEditable(false);
        textoPista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPista1ActionPerformed(evt);
            }
        });
        bgMadrid.add(textoPista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 120, -1));

        textoPista2.setEditable(false);
        textoPista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPista2ActionPerformed(evt);
            }
        });
        bgMadrid.add(textoPista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 120, -1));

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Pista 2:");
        bgMadrid.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 90, -1));

        textoPista3.setEditable(false);
        textoPista3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPista3ActionPerformed(evt);
            }
        });
        bgMadrid.add(textoPista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 130, -1));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Pista 3:");
        bgMadrid.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 50, -1));

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Pista 4:");
        bgMadrid.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 90, -1));

        textoPista4.setEditable(false);
        textoPista4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPista4ActionPerformed(evt);
            }
        });
        bgMadrid.add(textoPista4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 130, -1));

        bg.add(bgMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 410, 380));

        bgAero.setBackground(new java.awt.Color(204, 204, 204));
        bgAero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoAeroBaMa.setEditable(false);
        bgAero.add(textoAeroBaMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 810, -1));

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Aerovía Barcelona-Madrid");
        bgAero.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Aerovía Madrid-Barcelona");
        bgAero.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        textoAeroMaBa.setEditable(false);
        bgAero.add(textoAeroMaBa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 810, -1));

        bg.add(bgAero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 830, 140));

        bgBarcelona.setBackground(new java.awt.Color(204, 204, 204));
        bgBarcelona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Nº pasajeros en Aeropuerto:");
        bgBarcelona.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        textoNumPasajeros1.setEditable(false);
        bgBarcelona.add(textoNumPasajeros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 230, -1));

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Vía Aeropuerto:");
        bgBarcelona.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));

        textoBusA1.setEditable(false);
        textoBusA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoBusA1ActionPerformed(evt);
            }
        });
        bgBarcelona.add(textoBusA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 110, -1));

        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Hangar:");
        bgBarcelona.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        textoHangar1.setEditable(false);
        bgBarcelona.add(textoHangar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 340, -1));

        textoTaller1.setEditable(false);
        bgBarcelona.add(textoTaller1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 340, -1));

        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Taller:");
        bgBarcelona.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Vía Ciudad :");
        bgBarcelona.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        textoBusC1.setEditable(false);
        bgBarcelona.add(textoBusC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 110, -1));

        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Área de estacionamiento:");
        bgBarcelona.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        textoEstacionamiento1.setEditable(false);
        bgBarcelona.add(textoEstacionamiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 250, -1));

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Puerta 1 (E):");
        bgBarcelona.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, -1));

        textoPuerta7.setEditable(false);
        textoPuerta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta7ActionPerformed(evt);
            }
        });
        bgBarcelona.add(textoPuerta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 120, -1));

        textoPuerta8.setEditable(false);
        textoPuerta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta8ActionPerformed(evt);
            }
        });
        bgBarcelona.add(textoPuerta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 120, -1));

        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Puerta 2:");
        bgBarcelona.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 90, -1));

        textoPuerta9.setEditable(false);
        textoPuerta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta9ActionPerformed(evt);
            }
        });
        bgBarcelona.add(textoPuerta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 120, -1));

        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Puerta 3:");
        bgBarcelona.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 90, -1));

        textoPuerta10.setEditable(false);
        textoPuerta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta10ActionPerformed(evt);
            }
        });
        bgBarcelona.add(textoPuerta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 130, -1));

        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Puerta 4:");
        bgBarcelona.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 50, -1));

        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Puerta 5:");
        bgBarcelona.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, -1));

        textoPuerta11.setEditable(false);
        textoPuerta11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta11ActionPerformed(evt);
            }
        });
        bgBarcelona.add(textoPuerta11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 130, -1));

        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Puerta 6 (DE):");
        bgBarcelona.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 80, -1));

        textoPuerta12.setEditable(false);
        textoPuerta12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta12ActionPerformed(evt);
            }
        });
        bgBarcelona.add(textoPuerta12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 130, -1));

        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Aeropuerto de Barcelona");
        bgBarcelona.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 140, -1));

        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Área rodaje:");
        bgBarcelona.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        textoRodaje1.setEditable(false);
        bgBarcelona.add(textoRodaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 320, -1));

        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Pista 1:");
        bgBarcelona.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 90, -1));

        textoPista5.setEditable(false);
        textoPista5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPista5ActionPerformed(evt);
            }
        });
        bgBarcelona.add(textoPista5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 120, -1));

        textoPista6.setEditable(false);
        textoPista6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPista6ActionPerformed(evt);
            }
        });
        bgBarcelona.add(textoPista6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 120, -1));

        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Pista 2:");
        bgBarcelona.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 90, -1));

        textoPista7.setEditable(false);
        textoPista7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPista7ActionPerformed(evt);
            }
        });
        bgBarcelona.add(textoPista7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 130, -1));

        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Pista 3:");
        bgBarcelona.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 50, -1));

        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Pista 4:");
        bgBarcelona.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 90, -1));

        textoPista8.setEditable(false);
        textoPista8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPista8ActionPerformed(evt);
            }
        });
        bgBarcelona.add(textoPista8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 130, -1));

        bg.add(bgBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 410, 380));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 580));

        setBounds(0, 0, 846, 588);
    }// </editor-fold>//GEN-END:initComponents
    
    public void actualizarPasajeros(int pasajeros, String nombreAeropuerto){
        if("Madrid".equals(nombreAeropuerto)){
            textoNumPasajeros.setText(String.valueOf(pasajeros));
        }else{
            textoNumPasajeros1.setText(String.valueOf(pasajeros));
        }
    }
    
    private void botonPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPausarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPausarActionPerformed

    private void textoBusAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoBusAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoBusAActionPerformed

    private void textoPuerta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta1ActionPerformed

    private void textoPuerta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta2ActionPerformed

    private void textoPuerta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta3ActionPerformed

    private void textoPuerta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta4ActionPerformed

    private void textoPuerta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta5ActionPerformed

    private void textoPuerta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta6ActionPerformed

    private void textoPista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPista1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPista1ActionPerformed

    private void textoPista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPista2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPista2ActionPerformed

    private void textoPista3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPista3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPista3ActionPerformed

    private void textoPista4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPista4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPista4ActionPerformed

    private void textoBusA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoBusA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoBusA1ActionPerformed

    private void textoPuerta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta7ActionPerformed

    private void textoPuerta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta8ActionPerformed

    private void textoPuerta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta9ActionPerformed

    private void textoPuerta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta10ActionPerformed

    private void textoPuerta11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta11ActionPerformed

    private void textoPuerta12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta12ActionPerformed

    private void textoPista5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPista5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPista5ActionPerformed

    private void textoPista6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPista6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPista6ActionPerformed

    private void textoPista7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPista7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPista7ActionPerformed

    private void textoPista8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPista8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPista8ActionPerformed

    private void botonReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReanudarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonReanudarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgAero;
    private javax.swing.JPanel bgBarcelona;
    private javax.swing.JPanel bgMadrid;
    private javax.swing.JToggleButton botonPausar;
    private javax.swing.JToggleButton botonReanudar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField textoAeroBaMa;
    private javax.swing.JTextField textoAeroMaBa;
    private javax.swing.JTextField textoBusA;
    private javax.swing.JTextField textoBusA1;
    private javax.swing.JTextField textoBusC;
    private javax.swing.JTextField textoBusC1;
    private javax.swing.JTextField textoEstacionamiento;
    private javax.swing.JTextField textoEstacionamiento1;
    private javax.swing.JTextField textoHangar;
    private javax.swing.JTextField textoHangar1;
    private javax.swing.JTextField textoNumPasajeros;
    private javax.swing.JTextField textoNumPasajeros1;
    private javax.swing.JTextField textoPista1;
    private javax.swing.JTextField textoPista2;
    private javax.swing.JTextField textoPista3;
    private javax.swing.JTextField textoPista4;
    private javax.swing.JTextField textoPista5;
    private javax.swing.JTextField textoPista6;
    private javax.swing.JTextField textoPista7;
    private javax.swing.JTextField textoPista8;
    private javax.swing.JTextField textoPuerta1;
    private javax.swing.JTextField textoPuerta10;
    private javax.swing.JTextField textoPuerta11;
    private javax.swing.JTextField textoPuerta12;
    private javax.swing.JTextField textoPuerta2;
    private javax.swing.JTextField textoPuerta3;
    private javax.swing.JTextField textoPuerta4;
    private javax.swing.JTextField textoPuerta5;
    private javax.swing.JTextField textoPuerta6;
    private javax.swing.JTextField textoPuerta7;
    private javax.swing.JTextField textoPuerta8;
    private javax.swing.JTextField textoPuerta9;
    private javax.swing.JTextField textoRodaje;
    private javax.swing.JTextField textoRodaje1;
    private javax.swing.JTextField textoTaller;
    private javax.swing.JTextField textoTaller1;
    // End of variables declaration//GEN-END:variables
}
