/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;


import aeropuertos.Bus;
import aeropuertos.Central;
import java.awt.Color;


/**
 *
 * @author lucia
 */
public class MenuRemoto extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form Menu
     */
    public MenuRemoto() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        bgMadrid = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textoNumPasajeros = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textoHangar = new javax.swing.JTextField();
        textoTaller = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textoEstacionamiento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textoPuerta1 = new javax.swing.JTextField();
        textoPuerta2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textoPuerta3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textoPuerta4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textoPuerta5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textoPuerta6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textoRodaje = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        abrirPista_1 = new javax.swing.JToggleButton();
        cerrarPista_1 = new javax.swing.JToggleButton();
        cerrarPista_2 = new javax.swing.JToggleButton();
        abrirPista_2 = new javax.swing.JToggleButton();
        cerrarPista_3 = new javax.swing.JToggleButton();
        abrirPista_3 = new javax.swing.JToggleButton();
        cerrarPista_4 = new javax.swing.JToggleButton();
        abrirPista_4 = new javax.swing.JToggleButton();
        bgAero = new javax.swing.JPanel();
        textoAeroBaMa = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        textoAeroMaBa = new javax.swing.JTextField();
        icon = new javax.swing.JLabel();
        bgBarcelona = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        textoHangar1 = new javax.swing.JTextField();
        textoTaller1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        textoEstacionamiento1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        textoPuerta7 = new javax.swing.JTextField();
        textoPuerta8 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        textoPuerta9 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        textoPuerta10 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        textoPuerta11 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        textoPuerta12 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        textoRodaje1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        textoNumPasajeros1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        abrirPista_5 = new javax.swing.JToggleButton();
        cerrarPista_5 = new javax.swing.JToggleButton();
        abrirPista_6 = new javax.swing.JToggleButton();
        cerrarPista_6 = new javax.swing.JToggleButton();
        cerrarPista_7 = new javax.swing.JToggleButton();
        abrirPista_7 = new javax.swing.JToggleButton();
        cerrarPista_8 = new javax.swing.JToggleButton();
        abrirPista_8 = new javax.swing.JToggleButton();
        header = new javax.swing.JPanel();
        exitpanel = new javax.swing.JPanel();
        txtexit = new javax.swing.JLabel();
        javaeatlogo1 = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(204, 255, 255));
        bg.setForeground(new java.awt.Color(204, 204, 204));
        bg.setMaximumSize(new java.awt.Dimension(830, 580));
        bg.setMinimumSize(new java.awt.Dimension(830, 580));
        bg.setPreferredSize(new java.awt.Dimension(830, 580));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgMadrid.setBackground(new java.awt.Color(204, 255, 255));
        bgMadrid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nº pasajeros en Aeropuerto:");
        bgMadrid.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        textoNumPasajeros.setEditable(false);
        textoNumPasajeros.setText("0");
        textoNumPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNumPasajerosActionPerformed(evt);
            }
        });
        bgMadrid.add(textoNumPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 70, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hangar:");
        bgMadrid.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        textoHangar.setEditable(false);
        bgMadrid.add(textoHangar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 70, -1));

        textoTaller.setEditable(false);
        bgMadrid.add(textoTaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 70, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Taller:");
        bgMadrid.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Área de estacionamiento:");
        bgMadrid.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        textoEstacionamiento.setEditable(false);
        bgMadrid.add(textoEstacionamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 70, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Puerta 1 (E):");
        bgMadrid.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, -1));

        textoPuerta1.setEditable(false);
        textoPuerta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta1ActionPerformed(evt);
            }
        });
        bgMadrid.add(textoPuerta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 120, -1));

        textoPuerta2.setEditable(false);
        textoPuerta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta2ActionPerformed(evt);
            }
        });
        bgMadrid.add(textoPuerta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 120, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Puerta 2:");
        bgMadrid.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, -1));

        textoPuerta3.setEditable(false);
        textoPuerta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta3ActionPerformed(evt);
            }
        });
        bgMadrid.add(textoPuerta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 120, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Puerta 3:");
        bgMadrid.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, -1));

        textoPuerta4.setEditable(false);
        textoPuerta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta4ActionPerformed(evt);
            }
        });
        bgMadrid.add(textoPuerta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 130, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Puerta 4:");
        bgMadrid.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 50, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Puerta 5:");
        bgMadrid.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 90, -1));

        textoPuerta5.setEditable(false);
        textoPuerta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta5ActionPerformed(evt);
            }
        });
        bgMadrid.add(textoPuerta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 130, -1));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Puerta 6 (DE):");
        bgMadrid.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 80, -1));

        textoPuerta6.setEditable(false);
        textoPuerta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta6ActionPerformed(evt);
            }
        });
        bgMadrid.add(textoPuerta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 130, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Área rodaje:");
        bgMadrid.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        textoRodaje.setEditable(false);
        bgMadrid.add(textoRodaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 70, -1));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Pista 1:");
        bgMadrid.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 150, -1));

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Pista 2:");
        bgMadrid.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 150, -1));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Pista 3:");
        bgMadrid.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 150, -1));

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Pista 4:");
        bgMadrid.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 150, -1));

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aeropuerto de Madrid");
        bgMadrid.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        abrirPista_1.setText("Abrir");
        abrirPista_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPista_1ActionPerformed(evt);
            }
        });
        bgMadrid.add(abrirPista_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 70, -1));

        cerrarPista_1.setText("Cerrar");
        cerrarPista_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista_1ActionPerformed(evt);
            }
        });
        bgMadrid.add(cerrarPista_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 70, -1));

        cerrarPista_2.setText("Cerrar");
        cerrarPista_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista_2ActionPerformed(evt);
            }
        });
        bgMadrid.add(cerrarPista_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 70, -1));

        abrirPista_2.setText("Abrir");
        abrirPista_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPista_2ActionPerformed(evt);
            }
        });
        bgMadrid.add(abrirPista_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 70, -1));

        cerrarPista_3.setText("Cerrar");
        cerrarPista_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista_3ActionPerformed(evt);
            }
        });
        bgMadrid.add(cerrarPista_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 70, -1));

        abrirPista_3.setText("Abrir");
        abrirPista_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPista_3ActionPerformed(evt);
            }
        });
        bgMadrid.add(abrirPista_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 70, -1));

        cerrarPista_4.setText("Cerrar");
        cerrarPista_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista_4ActionPerformed(evt);
            }
        });
        bgMadrid.add(cerrarPista_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 70, -1));

        abrirPista_4.setText("Abrir");
        abrirPista_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPista_4ActionPerformed(evt);
            }
        });
        bgMadrid.add(abrirPista_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 70, -1));

        bg.add(bgMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 410, 380));

        bgAero.setBackground(new java.awt.Color(204, 255, 255));
        bgAero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoAeroBaMa.setEditable(false);
        bgAero.add(textoAeroBaMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 810, -1));

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Aerovía Barcelona-Madrid");
        bgAero.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Aerovía Madrid-Barcelona");
        bgAero.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        textoAeroMaBa.setEditable(false);
        bgAero.add(textoAeroMaBa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 810, -1));

        icon.setText("hay una foto");
        bgAero.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 80));

        bg.add(bgAero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 830, 200));

        bgBarcelona.setBackground(new java.awt.Color(204, 255, 255));
        bgBarcelona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Nº pasajeros en Aeropuerto:");
        bgBarcelona.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Hangar:");
        bgBarcelona.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        textoHangar1.setEditable(false);
        bgBarcelona.add(textoHangar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 80, -1));

        textoTaller1.setEditable(false);
        bgBarcelona.add(textoTaller1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Taller:");
        bgBarcelona.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Área de estacionamiento:");
        bgBarcelona.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        textoEstacionamiento1.setEditable(false);
        bgBarcelona.add(textoEstacionamiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 80, -1));

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Puerta 1 (E):");
        bgBarcelona.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, -1));

        textoPuerta7.setEditable(false);
        textoPuerta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta7ActionPerformed(evt);
            }
        });
        bgBarcelona.add(textoPuerta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 120, -1));

        textoPuerta8.setEditable(false);
        textoPuerta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta8ActionPerformed(evt);
            }
        });
        bgBarcelona.add(textoPuerta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 120, -1));

        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Puerta 2:");
        bgBarcelona.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, -1));

        textoPuerta9.setEditable(false);
        textoPuerta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta9ActionPerformed(evt);
            }
        });
        bgBarcelona.add(textoPuerta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 120, -1));

        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Puerta 3:");
        bgBarcelona.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, -1));

        textoPuerta10.setEditable(false);
        textoPuerta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta10ActionPerformed(evt);
            }
        });
        bgBarcelona.add(textoPuerta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 130, -1));

        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Puerta 4:");
        bgBarcelona.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 50, -1));

        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Puerta 5:");
        bgBarcelona.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 90, -1));

        textoPuerta11.setEditable(false);
        textoPuerta11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta11ActionPerformed(evt);
            }
        });
        bgBarcelona.add(textoPuerta11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 130, -1));

        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Puerta 6 (DE):");
        bgBarcelona.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 80, -1));

        textoPuerta12.setEditable(false);
        textoPuerta12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPuerta12ActionPerformed(evt);
            }
        });
        bgBarcelona.add(textoPuerta12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 130, -1));

        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Área rodaje:");
        bgBarcelona.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        textoRodaje1.setEditable(false);
        bgBarcelona.add(textoRodaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 80, -1));

        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Pista 1:");
        bgBarcelona.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 50, -1));

        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Pista 2:");
        bgBarcelona.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 150, -1));

        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Pista 3:");
        bgBarcelona.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 150, -1));

        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Pista 4:");
        bgBarcelona.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 150, -1));

        textoNumPasajeros1.setEditable(false);
        textoNumPasajeros1.setText("0");
        bgBarcelona.add(textoNumPasajeros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 70, -1));

        jLabel34.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Aeropuerto de Barcelona");
        bgBarcelona.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        abrirPista_5.setText("Abrir");
        abrirPista_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPista_5ActionPerformed(evt);
            }
        });
        bgBarcelona.add(abrirPista_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 70, -1));

        cerrarPista_5.setText("Cerrar");
        cerrarPista_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista_5ActionPerformed(evt);
            }
        });
        bgBarcelona.add(cerrarPista_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 70, -1));

        abrirPista_6.setText("Abrir");
        abrirPista_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPista_6ActionPerformed(evt);
            }
        });
        bgBarcelona.add(abrirPista_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 70, -1));

        cerrarPista_6.setText("Cerrar");
        cerrarPista_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista_6ActionPerformed(evt);
            }
        });
        bgBarcelona.add(cerrarPista_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 70, -1));

        cerrarPista_7.setText("Cerrar");
        cerrarPista_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista_7ActionPerformed(evt);
            }
        });
        bgBarcelona.add(cerrarPista_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 70, -1));

        abrirPista_7.setText("Abrir");
        abrirPista_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPista_7ActionPerformed(evt);
            }
        });
        bgBarcelona.add(abrirPista_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 70, -1));

        cerrarPista_8.setText("Cerrar");
        cerrarPista_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista_8ActionPerformed(evt);
            }
        });
        bgBarcelona.add(cerrarPista_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 70, -1));

        abrirPista_8.setText("Abrir");
        abrirPista_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPista_8ActionPerformed(evt);
            }
        });
        bgBarcelona.add(abrirPista_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 70, -1));

        bg.add(bgBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 410, 380));

        header.setBackground(new java.awt.Color(142, 181, 207));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitpanel.setBackground(new java.awt.Color(142, 181, 207));

        txtexit.setBackground(new java.awt.Color(0, 0, 0));
        txtexit.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        txtexit.setForeground(new java.awt.Color(0, 0, 0));
        txtexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtexit.setText("X");
        txtexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtexitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitpanelLayout = new javax.swing.GroupLayout(exitpanel);
        exitpanel.setLayout(exitpanelLayout);
        exitpanelLayout.setHorizontalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtexit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitpanelLayout.setVerticalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtexit, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        javaeatlogo1.setFont(new java.awt.Font("Roboto Condensed", 1, 36)); // NOI18N
        javaeatlogo1.setForeground(new java.awt.Color(255, 102, 0));

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(botonVolver)
                .addGap(71, 71, 71)
                .addComponent(javaeatlogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 615, Short.MAX_VALUE)
                .addComponent(exitpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(javaeatlogo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonVolver)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 40));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 620));

        setBounds(0, 0, 830, 619);
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarPasajeros(int pasajeros, String nombreAeropuerto) {
        if ("Madrid".equals(nombreAeropuerto)) {
            textoNumPasajeros.setText(String.valueOf(pasajeros));
        } else {
            textoNumPasajeros1.setText(String.valueOf(pasajeros));
        }
    }


    private void textoPuerta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta1ActionPerformed

    private void textoPuerta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta2ActionPerformed

    private void textoPuerta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta3ActionPerformed

    private void textoPuerta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta4ActionPerformed

    private void textoPuerta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta5ActionPerformed

    private void textoPuerta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta6ActionPerformed

    private void textoPuerta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta7ActionPerformed

    private void textoPuerta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta8ActionPerformed

    private void textoPuerta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta9ActionPerformed

    private void textoPuerta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta10ActionPerformed

    private void textoPuerta11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta11ActionPerformed

    private void textoPuerta12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPuerta12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPuerta12ActionPerformed

    private void txtexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseClicked
        Central.salir();
    }//GEN-LAST:event_txtexitMouseClicked

    private void txtexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseEntered
        txtexit.setForeground(Color.white);
    }//GEN-LAST:event_txtexitMouseEntered

    private void txtexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseExited
        txtexit.setForeground(Color.black);
    }//GEN-LAST:event_txtexitMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void textoNumPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNumPasajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNumPasajerosActionPerformed

    private void abrirPista_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPista_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirPista_1ActionPerformed

    private void cerrarPista_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarPista_1ActionPerformed

    private void cerrarPista_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarPista_2ActionPerformed

    private void abrirPista_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPista_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirPista_2ActionPerformed

    private void cerrarPista_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarPista_3ActionPerformed

    private void abrirPista_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPista_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirPista_3ActionPerformed

    private void cerrarPista_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarPista_4ActionPerformed

    private void abrirPista_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPista_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirPista_4ActionPerformed

    private void abrirPista_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPista_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirPista_5ActionPerformed

    private void cerrarPista_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarPista_5ActionPerformed

    private void abrirPista_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPista_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirPista_6ActionPerformed

    private void cerrarPista_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarPista_6ActionPerformed

    private void cerrarPista_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarPista_7ActionPerformed

    private void abrirPista_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPista_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirPista_7ActionPerformed

    private void cerrarPista_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarPista_8ActionPerformed

    private void abrirPista_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPista_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirPista_8ActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRemoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton abrirPista_1;
    private javax.swing.JToggleButton abrirPista_2;
    private javax.swing.JToggleButton abrirPista_3;
    private javax.swing.JToggleButton abrirPista_4;
    private javax.swing.JToggleButton abrirPista_5;
    private javax.swing.JToggleButton abrirPista_6;
    private javax.swing.JToggleButton abrirPista_7;
    private javax.swing.JToggleButton abrirPista_8;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgAero;
    private javax.swing.JPanel bgBarcelona;
    private javax.swing.JPanel bgMadrid;
    private javax.swing.JButton botonVolver;
    private javax.swing.JToggleButton cerrarPista_1;
    private javax.swing.JToggleButton cerrarPista_2;
    private javax.swing.JToggleButton cerrarPista_3;
    private javax.swing.JToggleButton cerrarPista_4;
    private javax.swing.JToggleButton cerrarPista_5;
    private javax.swing.JToggleButton cerrarPista_6;
    private javax.swing.JToggleButton cerrarPista_7;
    private javax.swing.JToggleButton cerrarPista_8;
    private javax.swing.JPanel exitpanel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel javaeatlogo1;
    private javax.swing.JTextField textoAeroBaMa;
    private javax.swing.JTextField textoAeroMaBa;
    private javax.swing.JTextField textoEstacionamiento;
    private javax.swing.JTextField textoEstacionamiento1;
    private javax.swing.JTextField textoHangar;
    private javax.swing.JTextField textoHangar1;
    private javax.swing.JTextField textoNumPasajeros;
    private javax.swing.JTextField textoNumPasajeros1;
    private javax.swing.JTextField textoPuerta1;
    private javax.swing.JTextField textoPuerta10;
    private javax.swing.JTextField textoPuerta11;
    private javax.swing.JTextField textoPuerta12;
    private javax.swing.JTextField textoPuerta2;
    private javax.swing.JTextField textoPuerta3;
    private javax.swing.JTextField textoPuerta4;
    private javax.swing.JTextField textoPuerta5;
    private javax.swing.JTextField textoPuerta6;
    private javax.swing.JTextField textoPuerta7;
    private javax.swing.JTextField textoPuerta8;
    private javax.swing.JTextField textoPuerta9;
    private javax.swing.JTextField textoRodaje;
    private javax.swing.JTextField textoRodaje1;
    private javax.swing.JTextField textoTaller;
    private javax.swing.JTextField textoTaller1;
    private javax.swing.JLabel txtexit;
    // End of variables declaration//GEN-END:variables
}
