package interfaz;

import aeropuertos.Servidor;
import java.awt.Color;


public class MenuRemoto extends javax.swing.JFrame {

    private int xMouse, yMouse;
    private Boolean[] listaPuertas = new Boolean[4];
    private Boolean[] listaPuertasBar = new Boolean[4];

    /**
     * Creates new form Menu
     */
    public MenuRemoto() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRemoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        initComponents();
        this.setLocationRelativeTo(null);
//        this.menu = menu;
        for (int i = 0; i < 4; i++) {
            listaPuertas[i] = true;
            listaPuertasBar[i] = true;
        }
        
        abrirPista_1.setSelected(true);
        abrirPista_2.setSelected(true);
        abrirPista_3.setSelected(true);
        abrirPista_4.setSelected(true);
        
        abrirPista_1B.setSelected(true);
        abrirPista_2B.setSelected(true);
        abrirPista_3B.setSelected(true);
        abrirPista_4B.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup1B = new javax.swing.ButtonGroup();
        buttonGroup2B = new javax.swing.ButtonGroup();
        buttonGroup3B = new javax.swing.ButtonGroup();
        buttonGroup4B = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        bgMadrid = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textoNumPasajeros = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textoHangar = new javax.swing.JTextField();
        textoTaller = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textoEstacionamiento = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textoRodaje = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        abrirPista_1 = new javax.swing.JToggleButton();
        cerrarPista_1 = new javax.swing.JToggleButton();
        cerrarPista_2 = new javax.swing.JToggleButton();
        abrirPista_2 = new javax.swing.JToggleButton();
        cerrarPista_3 = new javax.swing.JToggleButton();
        abrirPista_3 = new javax.swing.JToggleButton();
        cerrarPista_4 = new javax.swing.JToggleButton();
        abrirPista_4 = new javax.swing.JToggleButton();
        bgAero = new javax.swing.JPanel();
        textoAeroB = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        textoAeroM = new javax.swing.JTextField();
        bgBarcelona = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        textoHangar1 = new javax.swing.JTextField();
        textoTaller1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        textoEstacionamiento1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        textoRodaje1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        textoNumPasajeros1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        abrirPista_1B = new javax.swing.JToggleButton();
        cerrarPista_1B = new javax.swing.JToggleButton();
        abrirPista_2B = new javax.swing.JToggleButton();
        cerrarPista_2B = new javax.swing.JToggleButton();
        cerrarPista_3B = new javax.swing.JToggleButton();
        abrirPista_3B = new javax.swing.JToggleButton();
        cerrarPista_4B = new javax.swing.JToggleButton();
        abrirPista_4B = new javax.swing.JToggleButton();
        header = new javax.swing.JPanel();
        exitpanel = new javax.swing.JPanel();
        txtexit = new javax.swing.JLabel();
        javaeatlogo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(204, 255, 255));
        bg.setForeground(new java.awt.Color(204, 204, 204));
        bg.setMaximumSize(new java.awt.Dimension(830, 580));
        bg.setMinimumSize(new java.awt.Dimension(830, 580));
        bg.setPreferredSize(new java.awt.Dimension(830, 580));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgMadrid.setBackground(new java.awt.Color(204, 255, 255));
        bgMadrid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nº pasajeros en Aeropuerto:");
        bgMadrid.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        textoNumPasajeros.setEditable(false);
        textoNumPasajeros.setBackground(new java.awt.Color(255, 255, 255));
        textoNumPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNumPasajerosActionPerformed(evt);
            }
        });
        bgMadrid.add(textoNumPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 210, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hangar:");
        bgMadrid.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        textoHangar.setEditable(false);
        textoHangar.setBackground(new java.awt.Color(255, 255, 255));
        textoHangar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoHangarActionPerformed(evt);
            }
        });
        bgMadrid.add(textoHangar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 320, -1));

        textoTaller.setEditable(false);
        textoTaller.setBackground(new java.awt.Color(255, 255, 255));
        bgMadrid.add(textoTaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 330, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Taller:");
        bgMadrid.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Área de estacionamiento:");
        bgMadrid.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        textoEstacionamiento.setEditable(false);
        textoEstacionamiento.setBackground(new java.awt.Color(255, 255, 255));
        bgMadrid.add(textoEstacionamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 230, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Área rodaje:");
        bgMadrid.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        textoRodaje.setEditable(false);
        textoRodaje.setBackground(new java.awt.Color(255, 255, 255));
        bgMadrid.add(textoRodaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 300, -1));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Pista 1:");
        bgMadrid.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 150, -1));

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Pista 2:");
        bgMadrid.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 150, -1));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Pista 3:");
        bgMadrid.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 150, -1));

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Pista 4:");
        bgMadrid.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 150, -1));

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aeropuerto de Madrid");
        bgMadrid.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        buttonGroup1.add(abrirPista_1);
        abrirPista_1.setText("Abrir");
        abrirPista_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPista_1ActionPerformed(evt);
            }
        });
        bgMadrid.add(abrirPista_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 70, -1));

        buttonGroup1.add(cerrarPista_1);
        cerrarPista_1.setText("Cerrar");
        cerrarPista_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista_1ActionPerformed(evt);
            }
        });
        bgMadrid.add(cerrarPista_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 70, -1));

        buttonGroup2.add(cerrarPista_2);
        cerrarPista_2.setText("Cerrar");
        cerrarPista_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista_2ActionPerformed(evt);
            }
        });
        bgMadrid.add(cerrarPista_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 70, -1));

        buttonGroup2.add(abrirPista_2);
        abrirPista_2.setText("Abrir");
        abrirPista_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPista_2ActionPerformed(evt);
            }
        });
        bgMadrid.add(abrirPista_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 70, -1));

        buttonGroup3.add(cerrarPista_3);
        cerrarPista_3.setText("Cerrar");
        cerrarPista_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista_3ActionPerformed(evt);
            }
        });
        bgMadrid.add(cerrarPista_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 70, -1));

        buttonGroup3.add(abrirPista_3);
        abrirPista_3.setText("Abrir");
        abrirPista_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPista_3ActionPerformed(evt);
            }
        });
        bgMadrid.add(abrirPista_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 70, -1));

        buttonGroup4.add(cerrarPista_4);
        cerrarPista_4.setText("Cerrar");
        cerrarPista_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista_4ActionPerformed(evt);
            }
        });
        bgMadrid.add(cerrarPista_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 70, -1));

        buttonGroup4.add(abrirPista_4);
        abrirPista_4.setText("Abrir");
        abrirPista_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPista_4ActionPerformed(evt);
            }
        });
        bgMadrid.add(abrirPista_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 70, -1));

        bg.add(bgMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 410, 380));

        bgAero.setBackground(new java.awt.Color(204, 255, 255));
        bgAero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoAeroB.setEditable(false);
        textoAeroB.setBackground(new java.awt.Color(255, 255, 255));
        bgAero.add(textoAeroB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 810, -1));

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Aerovía Barcelona-Madrid");
        bgAero.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Aerovía Madrid-Barcelona");
        bgAero.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        textoAeroM.setEditable(false);
        textoAeroM.setBackground(new java.awt.Color(255, 255, 255));
        bgAero.add(textoAeroM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 810, -1));

        bg.add(bgAero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 830, 200));

        bgBarcelona.setBackground(new java.awt.Color(204, 255, 255));
        bgBarcelona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Nº pasajeros en Aeropuerto:");
        bgBarcelona.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Hangar:");
        bgBarcelona.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        textoHangar1.setEditable(false);
        textoHangar1.setBackground(new java.awt.Color(255, 255, 255));
        bgBarcelona.add(textoHangar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 320, -1));

        textoTaller1.setEditable(false);
        textoTaller1.setBackground(new java.awt.Color(255, 255, 255));
        bgBarcelona.add(textoTaller1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 330, -1));

        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Taller:");
        bgBarcelona.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Área de estacionamiento:");
        bgBarcelona.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        textoEstacionamiento1.setEditable(false);
        textoEstacionamiento1.setBackground(new java.awt.Color(255, 255, 255));
        bgBarcelona.add(textoEstacionamiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 230, -1));

        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Área rodaje:");
        bgBarcelona.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        textoRodaje1.setEditable(false);
        textoRodaje1.setBackground(new java.awt.Color(255, 255, 255));
        bgBarcelona.add(textoRodaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 300, -1));

        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Pista 1:");
        bgBarcelona.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 50, -1));

        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Pista 2:");
        bgBarcelona.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 150, -1));

        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Pista 3:");
        bgBarcelona.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 150, -1));

        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Pista 4:");
        bgBarcelona.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 150, -1));

        textoNumPasajeros1.setEditable(false);
        textoNumPasajeros1.setBackground(new java.awt.Color(255, 255, 255));
        bgBarcelona.add(textoNumPasajeros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 210, -1));

        jLabel34.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Aeropuerto de Barcelona");
        bgBarcelona.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        buttonGroup1B.add(abrirPista_1B);
        abrirPista_1B.setText("Abrir");
        abrirPista_1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPista_1BActionPerformed(evt);
            }
        });
        bgBarcelona.add(abrirPista_1B, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 70, -1));

        buttonGroup1B.add(cerrarPista_1B);
        cerrarPista_1B.setText("Cerrar");
        cerrarPista_1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista_1BActionPerformed(evt);
            }
        });
        bgBarcelona.add(cerrarPista_1B, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 70, -1));

        buttonGroup2B.add(abrirPista_2B);
        abrirPista_2B.setText("Abrir");
        abrirPista_2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPista_2BActionPerformed(evt);
            }
        });
        bgBarcelona.add(abrirPista_2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 70, -1));

        buttonGroup2B.add(cerrarPista_2B);
        cerrarPista_2B.setText("Cerrar");
        cerrarPista_2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista_2BActionPerformed(evt);
            }
        });
        bgBarcelona.add(cerrarPista_2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 70, -1));

        buttonGroup3B.add(cerrarPista_3B);
        cerrarPista_3B.setText("Cerrar");
        cerrarPista_3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista_3BActionPerformed(evt);
            }
        });
        bgBarcelona.add(cerrarPista_3B, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 70, -1));

        buttonGroup3B.add(abrirPista_3B);
        abrirPista_3B.setText("Abrir");
        abrirPista_3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPista_3BActionPerformed(evt);
            }
        });
        bgBarcelona.add(abrirPista_3B, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 70, -1));

        buttonGroup4B.add(cerrarPista_4B);
        cerrarPista_4B.setText("Cerrar");
        cerrarPista_4B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPista_4BActionPerformed(evt);
            }
        });
        bgBarcelona.add(cerrarPista_4B, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 70, -1));

        buttonGroup4B.add(abrirPista_4B);
        abrirPista_4B.setText("Abrir");
        abrirPista_4B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPista_4BActionPerformed(evt);
            }
        });
        bgBarcelona.add(abrirPista_4B, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 70, -1));

        bg.add(bgBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 410, 380));

        header.setBackground(new java.awt.Color(142, 181, 207));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitpanel.setBackground(new java.awt.Color(142, 181, 207));

        txtexit.setBackground(new java.awt.Color(0, 0, 0));
        txtexit.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        txtexit.setForeground(new java.awt.Color(0, 0, 0));
        txtexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtexit.setText("X");
        txtexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtexitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitpanelLayout = new javax.swing.GroupLayout(exitpanel);
        exitpanel.setLayout(exitpanelLayout);
        exitpanelLayout.setHorizontalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtexit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitpanelLayout.setVerticalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtexit, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        javaeatlogo1.setFont(new java.awt.Font("Roboto Condensed", 1, 36)); // NOI18N
        javaeatlogo1.setForeground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(javaeatlogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 615, Short.MAX_VALUE)
                .addComponent(exitpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(javaeatlogo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 40));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 620));

        setBounds(0, 0, 830, 619);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * 
     * @param listaNum
     * @param listaAerovia
     * @param aeropuerto 
     */
    public void actualizarCampoNumerico(String listaNum, String listaAerovia, String aeropuerto) {
        String[] listaNumerica = listaNum.split(",");
        if (aeropuerto.equals("Barcelona")) {
            textoNumPasajeros1.setText(listaNumerica[0]);
            textoHangar1.setText(listaNumerica[1]);
            textoEstacionamiento1.setText(listaNumerica[2]);
            textoRodaje1.setText(listaNumerica[3]);
            textoTaller1.setText(listaNumerica[4]);
            
            textoAeroB.setText(listaAerovia);
        } else {
            textoNumPasajeros.setText(listaNumerica[0]);
            textoHangar.setText(listaNumerica[1]);
            textoEstacionamiento.setText(listaNumerica[2]);
            textoRodaje.setText(listaNumerica[3]);
            textoTaller.setText(listaNumerica[4]);
            
            textoAeroM.setText(listaAerovia);
        }
    }
    
    /**
     * 
     * @param aeropuerto
     * @return 
     */
    public String obtenerDisPistas(String aeropuerto) {
        if (aeropuerto.equals("Barcelona")) {
            return arrayToString(listaPuertasBar);
        } else {
            return arrayToString(listaPuertas);
        }
    }
    
    /**
     * 
     * @param array
     * @return 
     */
    private String arrayToString(Boolean[] array) {
        String listaString = "";

        // Iterar sobre los elementos del array
        for (int i = 0; i < array.length; i++) {
            listaString += array[i];

            // Agregar una coma si no es el último elemento
            if (i < array.length - 1) {
                listaString += ",";
            }
        }

        return listaString;
    }

    private void txtexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseClicked
        Servidor.salir();
    }//GEN-LAST:event_txtexitMouseClicked

    private void txtexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseEntered
        txtexit.setForeground(Color.white);
    }//GEN-LAST:event_txtexitMouseEntered

    private void txtexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseExited
        txtexit.setForeground(Color.black);
    }//GEN-LAST:event_txtexitMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void textoNumPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNumPasajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNumPasajerosActionPerformed

    private void abrirPista_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPista_1ActionPerformed
        listaPuertas[0] = true;
    }//GEN-LAST:event_abrirPista_1ActionPerformed

    private void cerrarPista_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista_1ActionPerformed
        listaPuertas[0] = false;
    }//GEN-LAST:event_cerrarPista_1ActionPerformed

    private void cerrarPista_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista_2ActionPerformed
        listaPuertas[1] = false;
    }//GEN-LAST:event_cerrarPista_2ActionPerformed

    private void abrirPista_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPista_2ActionPerformed
        listaPuertas[1] = true;
    }//GEN-LAST:event_abrirPista_2ActionPerformed

    private void cerrarPista_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista_3ActionPerformed
        listaPuertas[2] = false;
    }//GEN-LAST:event_cerrarPista_3ActionPerformed

    private void abrirPista_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPista_3ActionPerformed
        listaPuertas[2] = true;
    }//GEN-LAST:event_abrirPista_3ActionPerformed

    private void cerrarPista_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista_4ActionPerformed
        listaPuertas[3] = false;
    }//GEN-LAST:event_cerrarPista_4ActionPerformed

    private void abrirPista_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPista_4ActionPerformed
        listaPuertas[3] = true;
    }//GEN-LAST:event_abrirPista_4ActionPerformed

    private void abrirPista_1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPista_1BActionPerformed
        listaPuertasBar[0] = true;
    }//GEN-LAST:event_abrirPista_1BActionPerformed

    private void cerrarPista_1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista_1BActionPerformed
        listaPuertasBar[0] = false;
    }//GEN-LAST:event_cerrarPista_1BActionPerformed

    private void abrirPista_2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPista_2BActionPerformed
        listaPuertasBar[1] = true;
    }//GEN-LAST:event_abrirPista_2BActionPerformed

    private void cerrarPista_2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista_2BActionPerformed
        listaPuertasBar[1] = false;
    }//GEN-LAST:event_cerrarPista_2BActionPerformed

    private void cerrarPista_3BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista_3BActionPerformed
        listaPuertasBar[2] = false;
    }//GEN-LAST:event_cerrarPista_3BActionPerformed

    private void abrirPista_3BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPista_3BActionPerformed
        listaPuertasBar[2] = true;
    }//GEN-LAST:event_abrirPista_3BActionPerformed

    private void cerrarPista_4BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPista_4BActionPerformed
        listaPuertasBar[3] = false;
    }//GEN-LAST:event_cerrarPista_4BActionPerformed

    private void abrirPista_4BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPista_4BActionPerformed
        listaPuertasBar[3] = true;
    }//GEN-LAST:event_abrirPista_4BActionPerformed

    private void textoHangarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoHangarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoHangarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRemoto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRemoto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRemoto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRemoto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MenuRemoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton abrirPista_1;
    private javax.swing.JToggleButton abrirPista_1B;
    private javax.swing.JToggleButton abrirPista_2;
    private javax.swing.JToggleButton abrirPista_2B;
    private javax.swing.JToggleButton abrirPista_3;
    private javax.swing.JToggleButton abrirPista_3B;
    private javax.swing.JToggleButton abrirPista_4;
    private javax.swing.JToggleButton abrirPista_4B;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgAero;
    private javax.swing.JPanel bgBarcelona;
    private javax.swing.JPanel bgMadrid;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup1B;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup2B;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup3B;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup4B;
    private javax.swing.JToggleButton cerrarPista_1;
    private javax.swing.JToggleButton cerrarPista_1B;
    private javax.swing.JToggleButton cerrarPista_2;
    private javax.swing.JToggleButton cerrarPista_2B;
    private javax.swing.JToggleButton cerrarPista_3;
    private javax.swing.JToggleButton cerrarPista_3B;
    private javax.swing.JToggleButton cerrarPista_4;
    private javax.swing.JToggleButton cerrarPista_4B;
    private javax.swing.JPanel exitpanel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel javaeatlogo1;
    private javax.swing.JTextField textoAeroB;
    private javax.swing.JTextField textoAeroM;
    private javax.swing.JTextField textoEstacionamiento;
    private javax.swing.JTextField textoEstacionamiento1;
    private javax.swing.JTextField textoHangar;
    private javax.swing.JTextField textoHangar1;
    private javax.swing.JTextField textoNumPasajeros;
    private javax.swing.JTextField textoNumPasajeros1;
    private javax.swing.JTextField textoRodaje;
    private javax.swing.JTextField textoRodaje1;
    private javax.swing.JTextField textoTaller;
    private javax.swing.JTextField textoTaller1;
    private javax.swing.JLabel txtexit;
    // End of variables declaration//GEN-END:variables
}
